// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../../types/supabase-types';

// Configurações do Supabase
const SUPABASE_URL = "https://osudrsvikewiyrubutko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_yok3BXSXZqSJFiK5CZTzww_-HSHsB5W";

// Configurações do cliente
const supabaseConfig = {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
};

// Cliente Supabase tipado
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY, 
  supabaseConfig
);

// Exportação padrão para compatibilidade
export default supabase;